### ISSUE TITLE
RSVP to workshop by commenting on this issue!

### ISSUE THREAD

**Issue by jjfiv** [CSWomenUMass/unix#1]
The workshop will be on **Tuesday, November 3** from **4-6p in CS150/151**, open to everyone, led by @belindanju.

Please fill out this short pre-workshop survey before the workshop: http://goo.gl/forms/gDIYOlzuH7

If you don't have access to a *nix machine or you're not sure if your Mac is setup with `brew`, check out our [bootcamp instructions](https://github.com/CSWomenUMass/tech-skills-bootcamp). If you have time to look at this before the workshop, you won't have to spend any time downloading and installing during the workshop.

**Comment by strubell** [comment]
I'll be there!

**Comment by etosch** [comment]
:heavy_check_mark: me, too

**Comment by belindanju** [comment]
- [x] Me as well!

**Comment by apoorvaraob** [comment]
Me too

**Comment by Shamya** [comment]
Me too

**Comment by cibelemf** [comment]
I will be there the usual time :+1:

**Comment by scottsman22000** [comment]
I will be there

**Comment by saulshanabrook** [comment]
Will be there!

**Comment by tao2020** [comment]
will be there

**Comment by mhjang** [comment]
for sure!  :dancer:

**Comment by sahilc0** [comment]
Me :facepunch: :+1:

**Comment by Ana-Lawrence** [comment]
I would be excited to join!

**Comment by Ana-Lawrence** [comment]
I would be excited to join!

**Comment by ssampang** [comment]
Me too

**Comment by akobre01** [comment]
In as well

**Comment by tasnani** [comment]
I'm coming!

**Comment by pllojan** [comment]
I'll be there

**Comment by rlingutla** [comment]
Count me in!

**Comment by imgemp** [comment]
I'll be there

**Comment by mmcmahon13** [comment]
I'm coming, sorry for the last minute-ness

**Comment by sblodgett** [comment]
I'll be there

**Comment by rbalon** [comment]
I'll be there

**Comment by dallessio** [comment]
I will be there, but I will be late.  I have a meeting until 4:30

**Comment by AnupamaP** [comment]
I'll be there for the first one hour!

**Comment by Sandhya0204** [comment]
I'll be there!

**Comment by DavidDeAngelo** [comment]
YEA!
